# Generated by Django 3.2.15 on 2022-09-04 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='The unique identifier of the instance this object belongs to. \n            Mandatory, unless a new instance to create is given.', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Timestamp when the record was created. The date and time \n            are displayed in the Timezone from where request is made. \n            e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC', verbose_name='Created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the record was modified. The date and \n            time are displayed in the Timezone from where request \n            is made. e.g. 2019-14-29T00:15:09Z for April 29, 2019 0:15:09 UTC\n            ', null=True, verbose_name='Updated')),
                ('name', models.CharField(help_text='The name of the budget item', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, help_text='The cost of the budget item.', max_digits=9, verbose_name='Cost')),
                ('quantity', models.PositiveSmallIntegerField(blank=True, default=1, help_text='If quantity is more than 1, specify the quality of the budget item. Defaults to 1.', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Budget Item',
                'verbose_name_plural': 'Budget Item',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('TRAVEL', 'TRAVEL'), ('GROCERIES', 'GROCERIES'), ('GIFT', 'GIFT'), ('RENT', 'RENT'), ('DRINKS', 'DRINKS'), ('FAMILY', 'FAMILY'), ('BILLS', 'BILLS'), ('GENERAL', 'GENERAL'), ('EATING_OUT', 'EATING_OUT'), ('ENTERTAINMENT', 'ENTERTAINMENT'), ('PERSONAL_CARE', 'PERSONAL_CARE'), ('TRANSPORTATION', 'TRANSPORTATION'), ('HEALTHCARE', 'HEALTHCARE'), ('HOME', 'HOME'), ('EDUCATION', 'EDUCATION'), ('SHOPPING', 'SHOPPING')], default='GENERAL', help_text='The category of the budget', max_length=14)),
                ('name', models.CharField(help_text='The name of the budget. This is the friendly name of the budget.', max_length=75)),
                ('budget_items', models.ManyToManyField(help_text='The items of the budget', to='budget.BudgetItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
