# Generated by Django 3.2.15 on 2022-09-04 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='linked_to_budget',
            field=models.BooleanField(default=False, help_text='A flag to determine if budget item is linked to a budget.'),
        ),
    ]
