# Generated by Django 3.2.15 on 2022-09-04 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget', '0002_budgetitem_linked_to_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='linked_to_budget',
            field=models.BooleanField(default=False, editable=False, help_text='A flag to determine if budget item is linked to a budget.'),
        ),
        migrations.AlterField(
            model_name='budgetitem',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
