# Generated by Django 3.2.15 on 2022-09-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20220904_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='name',
            field=models.CharField(help_text='The name of the budget item', max_length=20, unique=True),
        ),
    ]
