# Generated by Django 3.2.15 on 2022-09-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0005_auto_20220904_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1.0, help_text='The amount value of the budget item.', max_digits=9, verbose_name='Amount'),
        ),
    ]
