# Generated by Django 3.2.15 on 2022-09-04 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_alter_budgetitem_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budgetitem',
            old_name='type',
            new_name='item_type',
        ),
    ]
