# Budget categories choices

class ModelChoices:
    BUDGET_CATEGORY_TRAVEL = "TRAVEL"
    BUDGET_CATEGORY_GENERAL = "GENERAL"
    BUDGET_CATEGORY_BILLS = "BILLS"
    BUDGET_CATEGORY_FAMILY = "FAMILY"
    BUDGET_CATEGORY_DRINKS = "DRINKS"
    BUDGET_CATEGORY_RENT = "RENT"
    BUDGET_CATEGORY_GIFT = "GIFT"
    BUDGET_CATEGORY_GROCERIES = "GROCERIES"
    BUDGET_CATEGORY_SHOPPING = "SHOPPING"
    BUDGET_CATEGORY_EDUCATION = "EDUCATION"
    BUDGET_CATEGORY_HOME = "HOME"
    BUDGET_CATEGORY_HEALTHCARE = "HEALTHCARE"
    BUDGET_CATEGORY_TRANSPORTATION = "TRANSPORTATION"
    BUDGET_CATEGORY_PERSONAL_CARE = "PERSONAL_CARE"
    BUDGET_CATEGORY_ENTERTAINMENT = "ENTERTAINMENT"
    BUDGET_CATEGORY_EATING_OUT = "EATING_OUT"
    BUDGET_CATEGORY = (
        (BUDGET_CATEGORY_TRAVEL, BUDGET_CATEGORY_TRAVEL),
        (BUDGET_CATEGORY_GROCERIES, BUDGET_CATEGORY_GROCERIES),
        (BUDGET_CATEGORY_GIFT, BUDGET_CATEGORY_GIFT),
        (BUDGET_CATEGORY_RENT, BUDGET_CATEGORY_RENT),
        (BUDGET_CATEGORY_DRINKS, BUDGET_CATEGORY_DRINKS),
        (BUDGET_CATEGORY_FAMILY, BUDGET_CATEGORY_FAMILY),
        (BUDGET_CATEGORY_BILLS, BUDGET_CATEGORY_BILLS),
        (BUDGET_CATEGORY_GENERAL, BUDGET_CATEGORY_GENERAL),
        (BUDGET_CATEGORY_EATING_OUT, BUDGET_CATEGORY_EATING_OUT),
        (BUDGET_CATEGORY_ENTERTAINMENT, BUDGET_CATEGORY_ENTERTAINMENT),
        (BUDGET_CATEGORY_PERSONAL_CARE, BUDGET_CATEGORY_PERSONAL_CARE),
        (BUDGET_CATEGORY_TRANSPORTATION, BUDGET_CATEGORY_TRANSPORTATION),
        (BUDGET_CATEGORY_HEALTHCARE, BUDGET_CATEGORY_HEALTHCARE),
        (BUDGET_CATEGORY_HOME, BUDGET_CATEGORY_HOME),
        (BUDGET_CATEGORY_EDUCATION, BUDGET_CATEGORY_EDUCATION),
        (BUDGET_CATEGORY_SHOPPING, BUDGET_CATEGORY_SHOPPING)
    )


    BUDGET_ITEM_TYPE_INCOME = "INCOME"
    BUDGET_ITEM_TYPE_EXPENSES = "EXPENSE"
    BUDGET_ITEM_TYPE = (
        (BUDGET_ITEM_TYPE_INCOME, BUDGET_ITEM_TYPE_INCOME),
        (BUDGET_ITEM_TYPE_EXPENSES, BUDGET_ITEM_TYPE_EXPENSES)
    )